const navbarHTML = `
<nav class="site-navbar">
  <a href="/" class="logo-wrap" aria-label="Главная"><img src="/avatar.png" alt="Кэм"><span class="logo">kmcaq</span></a>
  <div class="nav-right">
    <a id="navStatus" class="nav-status" href="#" aria-label="Статус трансляции"><span id="navDot" class="nav-dot"></span><span id="navText">OFFLINE</span></a>
    <div class="social" aria-label="Социальные сети">
      <a href="https://www.twitch.tv/kmcaq" target="_blank" rel="noopener noreferrer" aria-label="Twitch"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 2h19v12l-5 5h-4l-4 4v-4H3V2Zm2 2v13h5v2.2l2.2-2.2H16l4-4V4H5Zm3 3h2v5H8V7Zm5 0h2v5h-2V7Z"/></svg></a>
      <a href="https://www.youtube.com/@kmcaq" target="_blank" rel="noopener noreferrer" aria-label="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M23 7.1a3 3 0 0 0-2.1-2.1C19.1 4.5 12 4.5 12 4.5s-7.1 0-8.9.5A3 3 0 0 0 1 7.1C.5 8.9.5 12 .5 12s0 3.1.5 4.9A3 3 0 0 0 3.1 19c1.8.5 8.9.5 8.9.5s7.1 0 8.9-.5a3 3 0 0 0 2.1-2.1c.5-1.8.5-4.9.5-4.9s0-3.1-.5-4.9ZM10 15.5v-7l6 3.5-6 3.5Z"/></svg></a>
      <a href="https://t.me/kmcaq" target="_blank" rel="noopener noreferrer" aria-label="Telegram"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 3.3 18 20.1c-.3 1.2-1 1.5-2 .9l-5.5-4.1-2.7 2.6c-.3.3-.5.5-1 .5l.4-5.7 10.4-9.4c.5-.4-.1-.6-.7-.2L4 12.6l-5.4-1.7c-1.2-.4-1.2-1.2.3-1.8l21-8.1c1.1-.4 2 .3 1.7 2.3Z"/></svg></a>
    </div>
    <div class="menu"><a href="/" data-nav="home">Главная</a><a href="/about/" data-nav="about">О канале</a><a href="/games/" data-nav="games">Игры</a><a href="/schedule/" data-nav="schedule">Расписание</a><a href="/links/" data-nav="links">Ссылки</a><a href="/feedback/" data-nav="feedback">Обратная связь</a></div>
  </div>
</nav>`;

const navbarStyles = `.site-navbar{position:fixed;top:10px;left:50%;transform:translateX(-50%);width:min(1120px,calc(100% - 24px));padding:10px 18px;display:flex;justify-content:space-between;align-items:center;background:rgba(18,15,30,.78);backdrop-filter:blur(22px);border:1px solid rgba(214,108,255,.16);border-radius:999px;z-index:1000;font-family:Nunito,sans-serif}.site-navbar *{box-sizing:border-box}.site-navbar .logo-wrap{display:flex;align-items:center;gap:12px;text-decoration:none}.site-navbar .logo-wrap img{width:44px;height:44px;border-radius:50%;border:2px solid rgba(214,108,255,.45)}.site-navbar .logo{font-size:28px;font-weight:800;color:#d66cff}.site-navbar .nav-right{display:flex;align-items:center;gap:18px}.site-navbar .nav-status{display:flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;background:rgba(180,120,255,.12);border:1px solid rgba(180,120,255,.25);font-size:14px;font-weight:700;text-decoration:none;color:white}.site-navbar .nav-status.live{background:rgba(255,77,109,.12);border-color:rgba(255,77,109,.35)}.site-navbar .nav-dot{width:10px;height:10px;border-radius:50%;background:#9c8db8}.site-navbar .social{display:flex;gap:10px}.site-navbar .social a{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.12);color:white}.site-navbar .social svg{width:20px;height:20px;fill:currentColor;display:block}.site-navbar .menu{display:flex;gap:22px}.site-navbar .menu a{position:relative;color:white;text-decoration:none;font-weight:700}.site-navbar .menu a:hover,.site-navbar .menu a.active{color:#d66cff}.site-navbar .menu a.active:after{content:"";position:absolute;left:0;bottom:-8px;width:100%;height:3px;border-radius:999px;background:linear-gradient(90deg,#d66cff,#9146ff)}
@media(max-width:980px){.site-navbar{top:8px;padding:8px 12px;border-radius:22px;align-items:flex-start}.site-navbar .nav-right{width:100%;justify-content:flex-end;gap:0}.site-navbar .nav-status,.site-navbar .social{display:none}.site-navbar .menu{display:flex;flex:1;justify-content:flex-end;align-items:center;gap:clamp(8px,2.5vw,18px);padding:6px 0 0 12px;flex-wrap:wrap}.site-navbar .menu a{font-size:13px;white-space:nowrap}.site-navbar .menu a.active:after{bottom:-5px;height:2px}.site-navbar .logo-wrap{flex-shrink:0}.site-navbar .logo-wrap img{width:38px;height:38px}.site-navbar .logo{font-size:21px}}
@media(max-width:520px){.site-navbar{width:calc(100% - 12px);padding:7px 9px}.site-navbar .logo-wrap{gap:7px}.site-navbar .logo{display:none}.site-navbar .logo-wrap img{width:36px;height:36px}.site-navbar .menu{gap:6px 10px;padding-left:6px}.site-navbar .menu a{font-size:12px}}
`;

function initNavbar(){const mount=document.getElementById("navbar");if(!mount)return false;if(!document.getElementById("navbar-styles")){const style=document.createElement("style");style.id="navbar-styles";style.textContent=navbarStyles;document.head.appendChild(style)}mount.innerHTML=navbarHTML;const path=window.location.pathname.replace(/index\.html$/i,"");let active="home";if(path.startsWith("/about/"))active="about";else if(path.startsWith("/games/"))active="games";else if(path.startsWith("/schedule/"))active="schedule";else if(path.startsWith("/links/"))active="links";else if(path.startsWith("/feedback/"))active="feedback";const link=mount.querySelector(`[data-nav="${active}"]`);if(link)link.classList.add("active");window.dispatchEvent(new Event("navbarReady"));return true}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initNavbar,{once:true});else initNavbar();
