const API = "https://admin.km-tamami.workers.dev";
const TOKEN_KEY = "admin_token";
const grid = document.getElementById("gamesGrid");
const login = document.getElementById("login");
const logout = document.getElementById("logout");
const add = document.getElementById("addGameBtn");
const save = document.getElementById("saveBtn");
let games = [];
const TIERS = ["NOW", "S", "A", "B", "C", "D", "F", "PLANNED"];
const TIER_NAMES = {NOW:"Играю сейчас",S:"S",A:"A",B:"B",C:"C",D:"D",F:"F",PLANNED:"В планах"};
const STATUSES = ["Прохожу", "Завершено", "Дроп", "В планах"];

function getToken(){return sessionStorage.getItem(TOKEN_KEY);}
(function restoreToken(){const hash=new URLSearchParams(location.hash.slice(1));const token=hash.get("token");if(token){sessionStorage.setItem(TOKEN_KEY,token);history.replaceState(null,"",location.pathname+location.search);}})();

async function authFetch(url,options={}){const token=getToken();const headers={...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(url,{...options,headers});if(res.status===401){sessionStorage.removeItem(TOKEN_KEY);location.href=`${API}/login`;throw new Error("Unauthorized");}return res;}
function normalizeStatus(status){if(status==="Пройдено")return "Завершено";if(status==="Запланировано")return "В планах";return STATUSES.includes(status)?status:"Прохожу";}
function normalizeTier(tier){return TIERS.includes(tier)?tier:"PLANNED";}

init();
async function init(){if(!getToken()){location.href=`${API}/login`;return;}try{const sessionRes=await authFetch(`${API}/session`);if(!sessionRes.ok)throw new Error(`Session check failed: ${sessionRes.status}`);const session=await sessionRes.json();if(!session.authenticated){sessionStorage.removeItem(TOKEN_KEY);location.href=`${API}/login`;return;}login.hidden=true;logout.hidden=false;add.hidden=false;save.hidden=false;const gamesRes=await authFetch(`${API}/games`);if(!gamesRes.ok)throw new Error(`Games load failed: ${gamesRes.status}`);const data=await gamesRes.json();games=Array.isArray(data)?data.map(game=>({...game,status:normalizeStatus(game.status),tier:normalizeTier(game.tier)})):[];render();}catch(error){console.error("Admin initialization failed:",error);}}

function render(){grid.innerHTML="";grid.style.cssText="display:flex;flex-direction:column;gap:8px;";TIERS.forEach(tier=>{const row=document.createElement("section");row.dataset.tier=tier;row.style.cssText="display:grid;grid-template-columns:88px 1fr;gap:10px;align-items:stretch;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:8px;min-height:92px;transition:.15s;";const label=document.createElement("div");label.textContent=TIER_NAMES[tier];label.style.cssText="display:flex;align-items:center;justify-content:center;border-radius:12px;background:rgba(214,108,255,.12);font-weight:800;";const zone=document.createElement("div");zone.style.cssText="display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:7px;align-items:start;min-height:74px;padding:2px;border-radius:12px;";zone.addEventListener("dragover",e=>{e.preventDefault();row.style.borderColor="rgba(214,108,255,.65)";});zone.addEventListener("dragleave",()=>{row.style.borderColor="rgba(255,255,255,.08)";});zone.addEventListener("drop",e=>{e.preventDefault();row.style.borderColor="rgba(255,255,255,.08)";const index=Number(e.dataTransfer.getData("text/plain"));if(!Number.isInteger(index)||!games[index])return;games[index].tier=tier;render();});games.forEach((g,i)=>{if(g.tier!==tier)return;const card=document.createElement("article");card.draggable=true;card.style.cssText="position:relative;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.08);border-radius:12px;overflow:hidden;cursor:grab;min-width:0;";card.innerHTML=`<img src="${g.cover}" alt="${g.name}" style="display:block;width:100%;aspect-ratio:460/215;object-fit:cover"><div style="padding:7px 8px"><strong style="display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${g.name}</strong><small style="color:#9ca3af">${g.status} · ⭐ ${g.rating??"—"}</small></div><div style="display:flex;gap:5px;padding:0 8px 8px"><button class="edit" type="button">✏️</button><button class="delete" type="button">🗑</button></div>`;card.addEventListener("dragstart",e=>{e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",String(i));card.style.opacity=".45";});card.addEventListener("dragend",()=>{card.style.opacity="1";});card.querySelector(".edit").onclick=()=>edit(i);card.querySelector(".delete").onclick=()=>{games.splice(i,1);render();};zone.append(card);});row.append(label,zone);grid.append(row);});}

function edit(i){const g=i===-1?{name:"",status:"В планах",rating:null,tier:"PLANNED",hours:0,deaths:0,playlist:"",cover:"../covers/placeholder.png"}:{...games[i]};g.status=normalizeStatus(g.status);g.tier=normalizeTier(g.tier);const modal=document.createElement("div");modal.style.cssText="position:fixed;inset:0;background:#0008;display:flex;justify-content:center;align-items:center;z-index:1000;";modal.innerHTML=`<div style="background:#151922;padding:28px;border-radius:22px;width:min(500px,92%)"><h2>${i===-1?"Новая игра":"Редактирование"}</h2><div style="display:flex;flex-direction:column;gap:12px;margin-top:16px"><input id="n" value="${g.name}"><label>Статус<select id="s"><option>Прохожу</option><option>Завершено</option><option>Дроп</option><option>В планах</option></select></label><label>Оценка<input id="r" type="number" min="0" max="10" step=".1" value="${g.rating??""}"></label><label>Тир<select id="t">${TIERS.map(t=>`<option value="${t}">${TIER_NAMES[t]}</option>`).join("")}</select></label><input id="h" type="number" value="${g.hours??0}"><input id="d" type="number" value="${g.deaths??0}"><input id="p" value="${g.playlist??""}"><button id="ok">Сохранить</button><button id="cancel">Отмена</button></div></div>`;document.body.append(modal);const statusInput=modal.querySelector("#s"),ratingInput=modal.querySelector("#r"),tierInput=modal.querySelector("#t");statusInput.value=g.status;ratingInput.value=g.rating??"";tierInput.value=g.tier;modal.querySelector("#cancel").onclick=()=>modal.remove();modal.querySelector("#ok").onclick=()=>{const updated={name:modal.querySelector("#n").value.trim(),status:normalizeStatus(statusInput.value),rating:ratingInput.value===""?null:Number(ratingInput.value),tier:normalizeTier(tierInput.value),hours:+modal.querySelector("#h").value,deaths:+modal.querySelector("#d").value,playlist:modal.querySelector("#p").value,cover:g.cover};if(i===-1)games.push(updated);else games[i]=updated;modal.remove();render();};}

add.onclick=()=>edit(-1);logout.onclick=()=>{sessionStorage.removeItem(TOKEN_KEY);location.href=`${API}/login`;};
save.onclick=async()=>{save.textContent="Сохраняю…";save.disabled=true;try{const res=await authFetch(`${API}/games`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({games})});if(!res.ok)throw new Error(`Save failed: ${res.status}`);save.textContent="✓ Сохранено";}catch(error){console.error("Games save failed:",error);save.textContent="Ошибка сохранения";}finally{save.disabled=false;setTimeout(()=>{save.textContent="💾 Сохранить изменения";},1500);}};